# Generated by Django 3.2.13 on 2022-06-25 01:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_developer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rfc', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='RFC invalido', regex='^([a-zA-Z&Ñ]{3,4}\\d{6}[a-zA-Z0-9]{3})$')])),
                ('telefono', models.IntegerField(max_length=10, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.DeleteModel(
            name='Developer',
        ),
    ]
