# Generated by Django 3.2.13 on 2022-06-25 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220624_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='telefono',
            field=models.IntegerField(null=True),
        ),
    ]
