# Generated by Django 3.2.13 on 2022-06-25 01:20

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_client_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='rfc',
            field=models.CharField(max_length=13, validators=[users.models.Client.validate_rfc]),
        ),
    ]
